"""Formatter utilities for converting code review findings to JIRA format.

This module handles converting Finding objects from code review into rich
JIRA-formatted issue descriptions with proper markdown, code blocks, and links.
"""

from typing import Optional, List
from app.models.review_findings import Finding
from app.models.jira_models import JIRAPriority


class JIRAFormatter:
    """Format code review findings for JIRA issues."""

    @staticmethod
    def get_severity_badge(severity: str) -> str:
        """
        Get JIRA-formatted severity badge.

        Args:
            severity: Severity level (CRITICAL, HIGH, MEDIUM, LOW, INFO)

        Returns:
            JIRA formatted severity indicator
        """
        severity_upper = severity.upper()
        badges = {
            "CRITICAL": "(!) *CRITICAL*",
            "HIGH": "(!) *HIGH*",
            "MEDIUM": "(i) *MEDIUM*",
            "LOW": "(-) *LOW*",
            "INFO": "(/) *INFO*",
        }
        return badges.get(severity_upper, f"*{severity_upper}*")

    @staticmethod
    def format_code_block(code: str, language: str = "python") -> str:
        """
        Format code block for JIRA.

        Args:
            code: Code snippet
            language: Programming language for syntax highlighting

        Returns:
            JIRA formatted code block
        """
        # JIRA uses {code:language} for code blocks
        return f"{{code:{language}}}\n{code}\n{{code}}"

    @staticmethod
    def format_link(text: str, url: str) -> str:
        """
        Format hyperlink for JIRA.

        Args:
            text: Link text
            url: URL

        Returns:
            JIRA formatted link [text|url]
        """
        return f"[{text}|{url}]"

    @staticmethod
    def format_panel(content: str, title: Optional[str] = None, panel_type: str = "info") -> str:
        """
        Format panel for JIRA (info, warning, error, success).

        Args:
            content: Panel content
            title: Optional panel title
            panel_type: Panel type (info, warning, error, success)

        Returns:
            JIRA formatted panel
        """
        if title:
            return f"{{panel:title={title}|borderStyle=solid|borderColor=#ccc|titleBGColor=#{panel_type}|bgColor=#fff}}\n{content}\n{{panel}}"
        return f"{{panel}}\n{content}\n{{panel}}"

    @classmethod
    def format_finding_description(
        cls,
        finding: Finding,
        pr_url: Optional[str] = None,
        repo_name: Optional[str] = None,
    ) -> str:
        """
        Format a Finding object as a plain text JIRA issue description.

        Args:
            finding: Code review finding
            pr_url: Optional PR URL for reference
            repo_name: Optional repository name

        Returns:
            Plain text issue description
        """
        lines = []

        # Header
        lines.append("Code Review Finding")
        lines.append("=" * 50)
        lines.append("")

        # Metadata
        file_path = finding.location.file_path if finding.location else "N/A"
        line_start = finding.location.line_start if finding.location else "N/A"

        lines.append(f"Severity: {finding.severity}")
        lines.append(f"Type: {finding.type}")
        lines.append(f"File: {file_path}")
        lines.append(f"Line: {line_start}")
        lines.append("")

        # Issue Description
        lines.append("Issue Description:")
        lines.append(finding.description)
        lines.append("")

        # Code Snippet (if available)
        if finding.location and finding.location.code_snippet:
            lines.append("Code Snippet:")
            lines.append(finding.location.code_snippet)
            lines.append("")

        # Recommendation
        lines.append("Recommended Fix:")
        lines.append(finding.recommendation)
        lines.append("")

        # Suggested Fix (if available)
        if finding.example_fix:
            lines.append("Suggested Code Change:")
            lines.append(finding.example_fix)
            lines.append("")

        # GitHub Reference
        if pr_url:
            lines.append("GitHub Reference:")
            lines.append(pr_url)
            lines.append("")

        # Footer
        lines.append("-" * 50)
        lines.append("This ticket was automatically generated by RepoAuditor AI")

        return "\n".join(lines)

    @classmethod
    def get_labels_from_finding(cls, finding: Finding) -> List[str]:
        """
        Generate JIRA labels from a finding.

        Args:
            finding: Code review finding

        Returns:
            List of labels
        """
        labels = ["code-review", "ai-generated"]

        # Add severity as label
        labels.append(finding.severity.lower())

        # Add type as label (normalized)
        finding_type = finding.type.lower().replace(" ", "-")
        labels.append(finding_type)

        return labels

    @classmethod
    def get_summary_from_finding(cls, finding: Finding) -> str:
        """
        Generate concise summary for JIRA issue title.

        Args:
            finding: Code review finding

        Returns:
            Issue summary (max 255 characters)
        """
        # Format: [SEVERITY] Type in file.py:line
        file_name = "unknown"
        line_info = ""

        if finding.location:
            if finding.location.file_path:
                # Get just the filename, not full path
                file_name = finding.location.file_path.split("/")[-1]
            if finding.location.line_start:
                line_info = f":{finding.location.line_start}"

        summary = f"[{finding.severity}] {finding.type} in {file_name}{line_info}"

        # Truncate if too long
        if len(summary) > 255:
            summary = summary[:252] + "..."

        return summary

    @classmethod
    def get_priority_from_finding(cls, finding: Finding) -> str:
        """
        Get JIRA priority name from finding severity.

        Args:
            finding: Code review finding

        Returns:
            JIRA priority name
        """
        return JIRAPriority.from_severity(finding.severity)
