"""Code reviewer agent using LangGraph."""

from typing import List

from app.agents.state import CodeReviewState
from app.integrations.gemini_client import GeminiClient
from app.integrations.github_client import GitHubClient
from app.models.webhook_events import FileChange
from app.utils.logger import setup_logger

logger = setup_logger(__name__)


async def fetch_pr_files(state: CodeReviewState) -> CodeReviewState:
    """
    Fetch files changed in the pull request.

    Args:
        state: Current workflow state

    Returns:
        Updated state with files
    """
    logger.info(f"Fetching files for PR #{state['pr_number']}")

    try:
        github_client = GitHubClient()
        files = github_client.get_pull_request_files(
            installation_id=state["installation_id"],
            repo_full_name=state["repo_full_name"],
            pr_number=state["pr_number"],
        )

        state["files"] = files
        state["files_analyzed"] = False

        logger.info(f"Retrieved {len(files)} files")

    except Exception as e:
        logger.error(f"Error fetching files: {e}")
        state["error"] = str(e)

    return state


async def analyze_code(state: CodeReviewState) -> CodeReviewState:
    """
    Analyze code changes using Gemini AI.

    Args:
        state: Current workflow state

    Returns:
        Updated state with analysis
    """
    if state.get("error"):
        return state

    logger.info("Analyzing code changes with AI")

    try:
        gemini_client = GeminiClient()
        analysis = await gemini_client.analyze_code_changes(
            files=state["files"],
            pr_title=state["pr_title"],
            pr_description=state["pr_description"],
        )

        state["analysis"] = analysis
        state["files_analyzed"] = True

        # Generate summary
        summary = await gemini_client.generate_review_summary(
            analysis=analysis,
            files_count=len(state["files"]),
        )
        state["summary"] = summary

        logger.info("Code analysis completed")

    except Exception as e:
        logger.error(f"Error analyzing code: {e}")
        state["error"] = str(e)

    return state


async def post_review(state: CodeReviewState) -> CodeReviewState:
    """
    Post review comments to GitHub.

    Args:
        state: Current workflow state

    Returns:
        Updated state
    """
    if state.get("error") or not state.get("analysis"):
        return state

    logger.info("Posting review to GitHub")

    try:
        github_client = GitHubClient()

        # Create review with summary
        review_body = f"""## AI Code Review

{state['summary']}

### Detailed Analysis

{state['analysis']}

---
*This review was generated by RepoAuditor AI*
"""

        github_client.create_review(
            installation_id=state["installation_id"],
            repo_full_name=state["repo_full_name"],
            pr_number=state["pr_number"],
            body=review_body,
            event="COMMENT",
            comments=state.get("comments", []),
        )

        state["review_posted"] = True
        logger.info("Review posted successfully")

    except Exception as e:
        logger.error(f"Error posting review: {e}")
        state["error"] = str(e)

    return state


def should_continue_review(state: CodeReviewState) -> str:
    """
    Determine if review workflow should continue.

    Args:
        state: Current workflow state

    Returns:
        Next node to execute
    """
    if state.get("error"):
        return "end"

    if not state.get("files_analyzed"):
        return "analyze"

    if not state.get("review_posted"):
        return "post"

    return "end"
