"""Command handlers for GitHub PR comments.

This module implements handlers for slash commands like /explain, /review, /help
that can be triggered via GitHub PR comments.
"""

from typing import Dict, Any, Optional
from datetime import datetime

from app.integrations.github_client import GitHubClient
from app.integrations.gemini_client import GeminiClient
from app.models.webhook_events import IssueCommentEvent, PullRequestReviewCommentEvent
from app.workflows.executor import execute_code_review_workflow
from app.utils.logger import setup_logger
from app.utils.helpers import (
    format_duration,
    format_cost,
    format_tokens,
    extract_error_context,
)

logger = setup_logger(__name__)


# ============================================================================
# Command: /explain - Explain PR Changes
# ============================================================================

async def handle_explain_command(event: IssueCommentEvent) -> None:
    """
    Handle /explain command to generate explanation of PR changes.

    Args:
        event: Issue comment event containing the command
    """
    repo_name = event.repository.full_name
    pr_number = event.issue.number
    installation_id = event.installation.id

    logger.info(
        f"Handling /explain command for {repo_name}#{pr_number}",
        extra={
            "extra_fields": {
                "repo_name": repo_name,
                "pr_number": pr_number,
                "commenter": event.comment.user.login,
            }
        }
    )

    start_time = datetime.utcnow()

    try:
        # Initialize clients
        github_client = GitHubClient()
        gemini_client = GeminiClient(use_flash=True)

        # Fetch PR details and diff
        pr_details = github_client.get_pr_details(
            repo_name=repo_name,
            pr_number=pr_number,
            installation_id=installation_id
        )

        pr_diff = github_client.get_pr_diff(
            repo_name=repo_name,
            pr_number=pr_number,
            installation_id=installation_id
        )

        # Generate explanation using Gemini
        logger.info(f"Generating explanation for PR #{pr_number}")

        explanation_prompt = f"""
You are a code review assistant. Explain the changes in this pull request in a clear, concise way.

**PR Title:** {pr_details.get('title', 'N/A')}
**PR Description:** {pr_details.get('body', 'No description provided')}

**Changes:**
{pr_diff}

Please provide:
1. A high-level summary of what this PR does (2-3 sentences)
2. Key changes by file (bullet points)
3. Potential impact or areas of concern
4. Any dependencies or related changes needed

Keep the explanation clear and accessible to both technical and non-technical reviewers.
"""

        response = await gemini_client.generate_text(explanation_prompt)

        # Calculate metrics
        end_time = datetime.utcnow()
        duration = (end_time - start_time).total_seconds()

        # Format response comment
        comment = f"""## 📝 PR Explanation

{response.explanation}

---
<details>
<summary>📊 Generation Metadata</summary>

- **Model:** {gemini_client.model_config.model_name}
- **Tokens Used:** {format_tokens(response.tokens_used)}
- **Cost:** {format_cost(response.cost_usd)}
- **Generation Time:** {format_duration(duration)}

</details>

*Generated by RepoAuditor AI in response to `/explain` command*
"""

        # Post explanation comment
        github_client.post_pr_comment(
            repo_name=repo_name,
            pr_number=pr_number,
            body=comment,
            installation_id=installation_id
        )

        logger.info(
            f"Posted explanation for PR #{pr_number}",
            extra={
                "extra_fields": {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                    "duration_seconds": duration,
                    "cost_usd": response.cost_usd,
                    "tokens_used": response.tokens_used,
                }
            }
        )

    except Exception as e:
        error_context = extract_error_context(e, repo_name, pr_number)

        logger.error(
            f"Failed to handle /explain command: {e}",
            exc_info=True,
            extra={"extra_fields": error_context}
        )

        # Post error comment
        try:
            github_client = GitHubClient()
            error_comment = f"""## ❌ Error Generating Explanation

Sorry, I encountered an error while generating the explanation:

```
{str(e)}
```

Please try again or contact support if the issue persists.
"""
            github_client.post_pr_comment(
                repo_name=repo_name,
                pr_number=pr_number,
                body=error_comment,
                installation_id=installation_id
            )
        except Exception as post_error:
            logger.error(f"Failed to post error comment: {post_error}")


# ============================================================================
# Command: /review - Trigger On-Demand Review
# ============================================================================

async def handle_review_command(event: IssueCommentEvent) -> None:
    """
    Handle /review command to trigger a code review on demand.

    Args:
        event: Issue comment event containing the command
    """
    repo_name = event.repository.full_name
    pr_number = event.issue.number
    installation_id = event.installation.id

    logger.info(
        f"Handling /review command for {repo_name}#{pr_number}",
        extra={
            "extra_fields": {
                "repo_name": repo_name,
                "pr_number": pr_number,
                "commenter": event.comment.user.login,
            }
        }
    )

    try:
        # Initialize GitHub client
        github_client = GitHubClient()

        # Post acknowledgment comment
        ack_comment = f"""## 🤖 Code Review Initiated

@{event.comment.user.login} requested a code review. Starting analysis now...

*This may take a minute or two depending on the size of the PR.*
"""

        github_client.post_pr_comment(
            repo_name=repo_name,
            pr_number=pr_number,
            body=ack_comment,
            installation_id=installation_id
        )

        # Fetch PR details
        pr_details = github_client.get_pr_details(
            repo_name=repo_name,
            pr_number=pr_number,
            installation_id=installation_id
        )

        # Execute full code review workflow
        logger.info(f"Starting code review workflow for PR #{pr_number}")

        result = await execute_code_review_workflow(
            repo_name=repo_name,
            pr_number=pr_number,
            installation_id=installation_id,
            pr_title=pr_details.get("title", ""),
            pr_author=pr_details.get("user", {}).get("login", "unknown"),
            pr_description=pr_details.get("body", ""),
            commit_sha=pr_details.get("head", {}).get("sha", ""),
        )

        if result.get("error"):
            logger.error(
                f"Review workflow failed for PR #{pr_number}: {result['error']}",
                extra={
                    "extra_fields": {
                        "repo_name": repo_name,
                        "pr_number": pr_number,
                        "error": result["error"],
                    }
                }
            )
        else:
            logger.info(
                f"Review workflow completed for PR #{pr_number}",
                extra={
                    "extra_fields": {
                        "repo_name": repo_name,
                        "pr_number": pr_number,
                        "findings_count": len(result.get("review_results", [])),
                    }
                }
            )

    except Exception as e:
        error_context = extract_error_context(e, repo_name, pr_number)

        logger.error(
            f"Failed to handle /review command: {e}",
            exc_info=True,
            extra={"extra_fields": error_context}
        )

        # Post error comment
        try:
            github_client = GitHubClient()
            error_comment = f"""## ❌ Review Failed

Sorry, I encountered an error while running the code review:

```
{str(e)}
```

Please try again or contact support if the issue persists.
"""
            github_client.post_pr_comment(
                repo_name=repo_name,
                pr_number=pr_number,
                body=error_comment,
                installation_id=installation_id
            )
        except Exception as post_error:
            logger.error(f"Failed to post error comment: {post_error}")


# ============================================================================
# Command: /help - Show Available Commands
# ============================================================================

async def handle_help_command(event: IssueCommentEvent) -> None:
    """
    Handle /help command to show available commands.

    Args:
        event: Issue comment event containing the command
    """
    repo_name = event.repository.full_name
    pr_number = event.issue.number
    installation_id = event.installation.id

    logger.info(
        f"Handling /help command for {repo_name}#{pr_number}",
        extra={
            "extra_fields": {
                "repo_name": repo_name,
                "pr_number": pr_number,
                "commenter": event.comment.user.login,
            }
        }
    )

    try:
        github_client = GitHubClient()

        help_comment = """## 🤖 RepoAuditor AI - Available Commands

I'm an AI-powered code review assistant. Here are the commands you can use:

### 📝 `/explain`
Get a detailed explanation of what this PR does, including:
- High-level summary of changes
- Key changes by file
- Potential impact areas
- Dependencies or related changes

**Usage:** Just comment `/explain` on the PR

---

### 🔍 `/review`
Trigger a comprehensive code review that checks for:
- Security vulnerabilities
- Performance issues
- Best practices violations
- Code quality concerns
- Potential bugs

**Usage:** Just comment `/review` on the PR

---

### ❓ `/help`
Show this help message with all available commands.

**Usage:** Just comment `/help` on the PR

---

### 🎯 Tips

- Commands are case-insensitive (`/Review` works same as `/review`)
- Commands must be at the start of your comment
- Reviews are automatically triggered when you open a PR or push new commits
- Use `/review` to manually re-run a review

---

### 🔧 Configuration

RepoAuditor AI uses:
- **AI Model:** Google Gemini 2.0 Flash
- **Auto-Review:** Enabled for PR open/sync/reopen events
- **Cache:** Reviews are cached for 1 hour to prevent duplicates

---

**Need more help?** Check the [documentation](https://github.com/your-org/repoauditor-ai) or contact support.

*Powered by RepoAuditor AI with Google Gemini*
"""

        github_client.post_pr_comment(
            repo_name=repo_name,
            pr_number=pr_number,
            body=help_comment,
            installation_id=installation_id
        )

        logger.info(
            f"Posted help message for PR #{pr_number}",
            extra={
                "extra_fields": {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                }
            }
        )

    except Exception as e:
        error_context = extract_error_context(e, repo_name, pr_number)

        logger.error(
            f"Failed to handle /help command: {e}",
            exc_info=True,
            extra={"extra_fields": error_context}
        )


# ============================================================================
# Command: /explain (for review comments on specific lines)
# ============================================================================

async def handle_explain_review_comment(event: PullRequestReviewCommentEvent) -> None:
    """
    Handle /explain command on a specific code line in a review comment.

    Args:
        event: Pull request review comment event containing the command
    """
    repo_name = event.repository.full_name
    pr_number = event.pull_request.number
    installation_id = event.installation.id
    file_path = event.comment.path
    line_number = event.comment.line or event.comment.original_line

    logger.info(
        f"Handling /explain review comment for {repo_name}#{pr_number} at {file_path}:{line_number}",
        extra={
            "extra_fields": {
                "repo_name": repo_name,
                "pr_number": pr_number,
                "file_path": file_path,
                "line_number": line_number,
                "commenter": event.comment.user.login,
            }
        }
    )

    start_time = datetime.utcnow()

    try:
        # Initialize clients
        github_client = GitHubClient()
        gemini_client = GeminiClient(use_flash=True)

        # Fetch PR diff
        pr_diff = github_client.get_pr_diff(
            repo_name=repo_name,
            pr_number=pr_number,
            installation_id=installation_id
        )

        # Extract context around the commented line
        # For simplicity, we'll explain based on the diff and file path
        explanation_prompt = f"""
You are a code review assistant. A reviewer has asked for an explanation of a specific code change.

**File:** {file_path}
**Line:** {line_number}

**Full PR Diff:**
{pr_diff}

Please explain:
1. What this specific change does
2. Why this change might have been made
3. Potential impacts or side effects
4. Any best practices or concerns related to this change

Focus specifically on the code at {file_path}:{line_number} but provide context from surrounding changes.
Keep the explanation concise (3-5 sentences).
"""

        response = await gemini_client.generate_text(explanation_prompt)

        # Calculate metrics
        end_time = datetime.utcnow()
        duration = (end_time - start_time).total_seconds()

        # Format response comment
        comment = f"""## 💡 Code Explanation

{response.explanation}

---
<details>
<summary>📊 Metadata</summary>

- **File:** `{file_path}:{line_number}`
- **Tokens:** {format_tokens(response.tokens_used)}
- **Cost:** {format_cost(response.cost_usd)}
- **Time:** {format_duration(duration)}

</details>

*Generated by RepoAuditor AI in response to `/explain` command*
"""

        # Reply to the review comment
        github_client.post_review_comment_reply(
            repo_name=repo_name,
            pr_number=pr_number,
            comment_id=event.comment.id,
            body=comment,
            installation_id=installation_id
        )

        logger.info(
            f"Posted explanation for {file_path}:{line_number}",
            extra={
                "extra_fields": {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                    "file_path": file_path,
                    "duration_seconds": duration,
                    "cost_usd": response.cost_usd,
                }
            }
        )

    except Exception as e:
        error_context = extract_error_context(e, repo_name, pr_number)
        error_context["file_path"] = file_path
        error_context["line_number"] = line_number

        logger.error(
            f"Failed to handle /explain review comment: {e}",
            exc_info=True,
            extra={"extra_fields": error_context}
        )

        # Post error reply
        try:
            github_client = GitHubClient()
            error_comment = f"❌ Sorry, I encountered an error while generating the explanation: `{str(e)}`"

            github_client.post_review_comment_reply(
                repo_name=repo_name,
                pr_number=pr_number,
                comment_id=event.comment.id,
                body=error_comment,
                installation_id=installation_id
            )
        except Exception as post_error:
            logger.error(f"Failed to post error reply: {post_error}")


# ============================================================================
# Command Router
# ============================================================================

async def route_command(
    command: str,
    event: IssueCommentEvent | PullRequestReviewCommentEvent
) -> None:
    """
    Route command to appropriate handler.

    Args:
        command: Command name (without / prefix)
        event: Comment event (issue comment or review comment)
    """
    logger.info(
        f"Routing command: {command}",
        extra={
            "extra_fields": {
                "command": command,
                "event_type": type(event).__name__,
            }
        }
    )

    # Handle review comment events (on specific code lines)
    if isinstance(event, PullRequestReviewCommentEvent):
        if command == "explain":
            await handle_explain_review_comment(event)
        else:
            logger.warning(f"Unknown review comment command: {command}")
            return

    # Handle issue comment events (on PR in general)
    elif isinstance(event, IssueCommentEvent):
        if command == "explain":
            await handle_explain_command(event)
        elif command == "review":
            await handle_review_command(event)
        elif command == "help":
            await handle_help_command(event)
        else:
            logger.warning(f"Unknown command: {command}")
            # Optionally post a "command not found" message
            try:
                github_client = GitHubClient()
                github_client.post_pr_comment(
                    repo_name=event.repository.full_name,
                    pr_number=event.issue.number,
                    body=f"❓ Unknown command: `/{command}`. Type `/help` to see available commands.",
                    installation_id=event.installation.id
                )
            except Exception as e:
                logger.error(f"Failed to post unknown command message: {e}")
